config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails, only: [ :new, :create, :show ] do
    resources :doses, only: [ :new, :create ]
  end
  resources :doses, only: [ :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses 
    validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: {scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses
    has_many :cocktails, through: :doses 
    validates :name, presence: true, uniqueness: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

    def index
        @cocktails = Cocktail.all
    end

    def show
        @cocktail = Cocktail.find(params[:id])
        @dose = Dose.new
    end

    def new
        @cocktail = Cocktail.new
    end

    def create
        @cocktail = Cocktail.new(cocktails_params)
        if @cocktail.save
            redirect_to cocktail_path(id: @cocktail.id)
        else
            render :new
        end
    end

    private

    def cocktails_params
        params.require(:cocktail).permit(:name)
    end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

    def create 
        @dose = Dose.new(doses_params)
        @cocktail = Cocktail.find(params[:cocktail_id])
        @dose.cocktail = @cocktail
        if @dose.save
            redirect_to cocktail_path(id: @cocktail.id)
        else
            render :new
        end
    end

    def destroy
        @dose = Dose.find(params[:id])
        @cocktail = @dose.cocktail
        @dose.delete
        redirect_to cocktail_path(@cocktail)
    end

    private

    def doses_params
        params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class = "list">
  <% @cocktails.each do |cocktail| %>
    <h1><%= cocktail.name %></h1>
    <% end %>
</div>

app/views/cocktails/new.html.erb
<h1> New Cocktail </h1>

<%= form_for(@cocktail) do |n| %>
  <%= n.label :name %>
  <%= n.text_field :name %>
  <%= n.submit %>
<% end %>

<%= link_to "Back to list", cocktails_path %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<%= link_to "Back to list", cocktails_path %>

<%= simple_form_for [@cocktail, @dose] do |d| %>
  <%= d.input :description %>
  <%= d.association :ingredient %>
  <%= d.button :submit %>
<% end %>

<% @cocktail.doses.each do |dose| %>
    <span><%= dose.ingredient.name %></span>
    <%= dose.description %>
    <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash destroy_dose"></i>
    <% end %>
<% end %>



<%# <% @cocktail.doses.each do |dose| %>
    <%# <><%= @dose.content %>
<%# <% end %> 

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |d| %>
  <%= d.input :description %>
  <%= d.association :ingredient %>
  <%= d.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>